### ISSUE TITLE
Cue ID not working

### ISSUE THREAD

**Issue by Gibarr15** [bitfocus/companion-module-figure53-qlab-advance#93]
Every time i set a cue ID to to be selected and play qlab does nothing. As far as i can tell the button in companion is either sending the wrong compand and qlab isnt loading it or it is not being set at all. Qlab in the past would select a cue id and play it when a companion button was hit. This did not matter if qlab had a file selected. Now even if a cue id is selected and go is hit in companion nothing happens on qlab's end.

**Comment by istnv** [comment]
Which version of Companion and QLab module?
This was fixed recently. QLab changed some ID commands to be more consistent with other ID requests. 
Both new and old versions were supported until QLab 5.2.

**Comment by Gibarr15** [comment]
5.2.1 on qlab and Companion is on 3.0.0+6049-stable-126f27e8  on the mac arm version

**Comment by istnv** [comment]
It is fixed in the beta release (3.1.0). Try that to see if everything works. 
Otherwise I'll try to figure out how to make a package for Mac arm for you until Companion 3.0.1 is published.

**Comment by Gibarr15** [comment]
Okay thanks ill try that, for refrence my companion running on a raspberry pi [2.2.0 (2.2.0-8639f9ba-3558)](https://bitfocus.io/companion/) works just fine under qlab but qlab with feedback does not work on my raspberry pi or macbook.

**Comment by istnv** [comment]
There has been a LOT of protocol updates in the feedback version since then. No way to update anything earlier than 3.0 since that was a major (breaking) change to Companion modules.

**Comment by Gibarr15** [comment]
Unfortunately that still doesn't seem to have fixed my issue.

**Comment by istnv** [comment]
Can you send me your show file? It is nearly impossible to locate these issues without one sometimes.
Export the button page from companion as well. I'll look into it later tonight.

**Comment by Gibarr15** [comment]
So it seems to be a udp issue on my end. I restarted everything again and turned tcp on qlab and companion and now the start cue id seems to work in companion on 3.0.0

**Comment by istnv** [comment]
That would do it. The module internally checks the QLab version and adjusts the Goto/Start Cue ID command appropriately. UDP does not query the version, so would not know which command to use.

**Comment by Gibarr15** [comment]
okay that makes sense, I am still not getting the goto cue id or go to cue to work, buyt the start cue id works just fine. Thanks for help.

**Comment by istnv** [comment]
I use Goto (Cue ID) about 30 times in one of our current shows. I can not duplicate any failures with those commands.

**Comment by istnv** [comment]
I also tested Companion Beta (v3.1.0) on my Raspberry Pi. Cue ID works as expected.

**Comment by Gibarr15** [comment]
Awesome! thanks for the update! i was thinking about updating my "companion pi" but didnt want to do that after seeing the qlab issue I was having. Thanks for all your help!
\

**Comment by istnv** [comment]
Found an issue that would prevent any command from working when using UDP mode.

**Comment by Gibarr15** [comment]
Thanks!
